displayName=Item Stats Improved
author=TheCosmicNebula
description=Show information about food and potion effects - now with modifier key and other misc improvements
tags=food, inventory, overlay, potion
plugins=com.itemstatsimproved.ItemStatsImprovedPlugin
build=standard